global : {
    custom-dir : ["/var/lib/puppet/lib/facter"]
    # We don't use external facts distributed via puppet, but harmless to
    # retain support
    external-dir : ["/var/lib/puppet/facts.d"]
}
