#!/bin/sh
# SPDX-License-Identifier: Apache-2.0

# If pbuilder is called by gbp DIST is stored in GBP_PBUILDER_DIST
DIST=${GBP_PBUILDER_DIST:-$DIST}

if [ "$MAPS" = "yes" ] && [ "$DIST" = "bookworm" ]; then
    cat > /etc/apt/sources.list.d/wikimedia-maps.list <<-'EOF'
    deb http://apt.wikimedia.org/wikimedia bookworm-wikimedia component/maps
    deb-src http://apt.wikimedia.org/wikimedia bookworm-wikimedia component/maps
EOF
    apt-get update
fi
